 // Load your images on page-load
    function preloader() {
        const imagesList = [
           "./img/background.jpg",
           "./img/facebook.jpg",
           "./img/ins.jpg",
           "./img/logo.svg",
           "./img/solar.jpg",
           "./img/we.jpg",
           "./img/youtube.jpg"
        ];
        const images = [];
        for (let i = 0; i < imagesList.length; i++) {
            images[i] = new Image();
            images[i].src = imagesList[i];
        }

        // Images ready to be used:
        console.log(`Preloaded images:\n\t${images[0].src}\n\t${images[1].src}\n\t${images[2].src}`);
    };    
    window.addEventListener("load", preloader);

// DATA RESOURCES
const resources = [
	{
		headingText: "New Energy Vehicles",
		bodyText: "Battery Electric Vehicles is a kind of car that uses a single battery as the energy storage power source. It uses the battery as the energy storage power source to provide electrical energy to the motor through the battery, drive the motor to run, and then drive the car. At the same time, pure electric vehicles also use batteries to store electrical energy, drive the motor to run, and allow the vehicle to run normally.Hybrid Electric Vehicle's main drive system is composed of at least two single drive systems that can operate simultaneously. Generally refers to hybrid electric vehicles.",
		imgUrl: "./img/nev.jpg",
        imgAlt: "New Energy Vehicles"
    },
	{
		headingText: "Wind Energy",
		bodyText: "Wind energy is generated by the flow of air. A form of conversion of solar energy. The total reserves of wind energy resources are huge, and the technologically developable energy in a year is about 5.3X10^13 kWh. Wind energy is a renewable and clean energy. Under certain technical conditions, wind energy can be developed and utilized as an important energy source. Wind energy density is the wind power available per unit area facing the wind, which is proportional to the power of the wind speed and the air density.",
		imgUrl: "./img/we.jpg",
        imgAlt: "Wind Energy"
        
    },
	{
		headingText: "Solar Energy",
		bodyText: "Solar energy refers to the heat radiation energy of the sun, which is mainly represented by the sun's rays. Solar power generation is an emerging renewable energy source. There are two ways to use solar energy: light-to-heat conversion and photoelectric conversion. In modern times, it is generally used to generate electricity or provide energy for water heaters. Since ancient times, humans have also understood that the sun can dry objects and use them as a method of making food, such as salt making and salted fish. With the declining fossil fuels, solar energy has become an important part of mankind's energy use and has been continuously developed.",
		imgUrl: "./img/solar.jpg",
        imgAlt: "Solar Energy"
    }
];
 /* Get all buttons in a NODE LIST of buttons (array like structure) */
let $buttons = document.querySelectorAll('#controls button');
let $content = document.querySelector(".loaded-content");

/* When loading pages */
function loading() {
	$content.innerHTML = ` <div class="box">
                            <h1>${resources[0].headingText}</h1>
                            <img src="${resources[0].imgUrl}" alt="${resources[0].imgAlt}">
                            <p>${resources[0].bodyText}</p>
                             </div>`;
}
window.addEventListener("load", loading);


let controls = document.getElementById("controls");
let controlbtn = controls.getElementsByClassName("buttons");

/* control each button's active */
function ctrlBtns () {
		let actives = document.getElementsByClassName("active");
		actives[0].className = actives[0].className.replace(" active", "");
		this.className += " active";
	}

/* The first button in a NODE LIST of buttons will initially have the id: active-button - this will uniquely style the active button (CSS rule).*/
for (let i = 0; i < controlbtn.length; i++) {
	controlbtn[i].addEventListener("click", ctrlBtns);
}


/*Event Handler -  handleSelection function*/
function handleSelection(events) {
	let clickButton = events.target;
	let btnId = clickButton.id;
    /*Use conditional and event-object to check which button is clicked
        and based on that, create HTML with the data inside the back-ticks*/
	if (btnId == "b1") {
		$content.innerHTML = `<h1>${resources[0].headingText}</h1>
                              <img src="${resources[0].imgUrl}" alt="${resources[0].imgAlt}">
                              <p>${resources[0].bodyText}</p>`;
	} else if (btnId == "b2") {
		$content.innerHTML = `<h1>${resources[1].headingText}</h1>
                              <img src="${resources[1].imgUrl}"  alt="${resources[1].imgAlt}">
                              <p>${resources[1].bodyText}</p>`;
	} else if (btnId == "b3") {
		$content.innerHTML = `<h1>${resources[2].headingText}</h1>
                              <img src="${resources[2].imgUrl}" alt="${resources[2].imgAlt}">
                              <p>${resources[2].bodyText}</p>`;
	}
}

/* 
    Register all buttons to click event. The event-handler handleSelection will listen 
    for this event to happen. */ 
for (let i = 0; i < $buttons.length; i++) {
	$buttons[i].addEventListener("click", handleSelection);
}